import React, { useState } from 'react';

function money(value) { return Number(value || 0).toLocaleString('id-ID'); }
function formatDate(value) { if (!value) return '—'; const date = new Date(value); if (Number.isNaN(date.getTime())) return String(value); return new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(date); }

const printStyles = `
.print-preview-backdrop{position:fixed;inset:0;z-index:200;background:rgba(15,23,42,.55);display:grid;place-items:center;padding:20px}
.print-preview{width:min(1100px,100%);height:min(92vh,900px);display:flex;flex-direction:column;background:#eef0f3;border-radius:12px;overflow:hidden;box-shadow:0 24px 80px rgba(15,23,42,.25)}
.print-toolbar{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 18px;background:#fff;border-bottom:1px solid #dfe3e8}
.print-toolbar h2{margin:0;font-size:17px}.print-toolbar-actions{display:flex;gap:7px;flex-wrap:wrap}.print-canvas{overflow:auto;padding:24px}
.invoice-sheet{width:min(900px,100%);min-height:1120px;margin:0 auto;padding:28px;background:#fff;color:#202938;font-family:Arial,Helvetica,sans-serif;font-size:12px}
.invoice-head{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #2f6fed;padding-bottom:16px}.invoice-company{font-size:18px;font-weight:800}.invoice-subtitle{margin-top:4px;color:#687386}.invoice-title{text-align:right}.invoice-title h1{margin:0;font-size:24px}.invoice-title strong{display:block;margin-top:6px;font-size:14px}
.invoice-meta{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:18px 0}.invoice-label{font-size:10px;color:#6b7280;text-transform:uppercase;font-weight:700;margin-bottom:6px}.invoice-items{border:1px solid #dfe3e8;border-radius:6px;overflow:hidden}.invoice-items table{width:100%;border-collapse:collapse}.invoice-items th{background:#f3f4f6;text-align:left;padding:9px;font-size:10px;color:#596273}.invoice-items td{padding:9px;border-top:1px solid #e7e9ed;vertical-align:top}.invoice-num{text-align:right;white-space:nowrap}
.invoice-totals{margin:16px 0 0 auto;width:330px}.invoice-totals>div{display:flex;justify-content:space-between;padding:5px 0}.invoice-totals .invoice-grand{font-size:15px;font-weight:800;border-top:1px solid #ccd2db;margin-top:4px;padding-top:9px}.invoice-payment{margin-top:20px;padding:12px;border:1px solid #dfe3e8;border-radius:6px}.invoice-payment-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.invoice-payment-grid span{display:block;font-size:10px;color:#6b7280;text-transform:uppercase}.invoice-payment-grid strong{display:block;margin-top:4px}.invoice-payment-history{margin-top:12px;padding:10px 12px;border:1px solid #dfe3e8;border-radius:6px}.invoice-payment-history>div:not(.invoice-label){display:flex;justify-content:space-between;padding:4px 0}.invoice-footer{margin-top:36px;padding-top:12px;border-top:1px solid #dfe3e8;color:#6b7280;font-size:10px}
.thermal-mode .print-canvas{padding:20px;background:#dfe1e5}.thermal-mode .invoice-sheet{width:80mm;min-height:auto;padding:8mm 4mm;font-size:11px}.thermal-mode .invoice-head{display:block;text-align:center;border-bottom:0;padding-bottom:8px}.thermal-mode .invoice-company{font-size:16px}.thermal-mode .invoice-title{text-align:center}.thermal-mode .invoice-title h1{font-size:14px;margin-top:4px}.thermal-mode .invoice-meta{display:block;margin:10px 0}.thermal-mode .invoice-meta>div{margin-bottom:7px}.thermal-mode .invoice-items{border:0;border-radius:0}.thermal-mode .invoice-items th,.thermal-mode .invoice-items td:nth-child(3),.thermal-mode .invoice-items td:nth-child(4){display:none}.thermal-mode .invoice-items td{padding:5px 0;border-top:0}.thermal-mode .invoice-totals{width:100%;margin-top:8px}.thermal-mode .invoice-payment{border:0;border-top:1px dashed #777;border-radius:0;padding:8px 0}.thermal-mode .invoice-payment-grid{display:block}.thermal-mode .invoice-payment-grid>div{display:flex;justify-content:space-between;padding:2px 0}.thermal-mode .invoice-payment-grid span,.thermal-mode .invoice-payment-grid strong{font-size:11px}.thermal-mode .invoice-payment-history{border:0;border-top:1px dashed #777;border-radius:0;padding:8px 0}.thermal-mode .invoice-footer{text-align:center;margin-top:18px}
@media print{body>*{display:none!important}.print-preview-backdrop{display:block!important;position:static!important;background:#fff!important;padding:0!important}.print-preview{width:auto!important;height:auto!important;display:block!important;background:#fff!important;box-shadow:none!important;border-radius:0!important}.print-toolbar{display:none!important}.print-canvas{padding:0!important;overflow:visible!important;background:#fff!important}.invoice-sheet{margin:0!important}.thermal-mode .invoice-sheet{width:80mm!important}}
@media(max-width:700px){.print-toolbar{align-items:flex-start;flex-direction:column}.print-canvas{padding:12px}.invoice-meta{grid-template-columns:1fr}.invoice-title{text-align:left}.invoice-totals{width:100%}.invoice-payment-grid{grid-template-columns:1fr}}
`;

export default function InvoicePrint({ order, items, payments, grandTotal, totalPaid, balance, paymentStatus }) {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState('A4');
  function print() { window.print(); }
  return <>
    <button className="button secondary" type="button" onClick={() => setOpen(true)}>Print</button>
    {open && <div className="print-preview-backdrop" role="presentation">
      <style>{printStyles}</style>
      <div className={`print-preview ${mode === 'THERMAL' ? 'thermal-mode' : ''}`} role="dialog" aria-modal="true" aria-labelledby="print-title">
        <div className="print-toolbar"><div><p className="eyebrow">PRINT PREVIEW</p><h2 id="print-title">Sales Order Invoice</h2></div><div className="print-toolbar-actions"><button className={`button ${mode === 'A4' ? 'primary' : 'secondary'}`} type="button" onClick={() => setMode('A4')}>A4</button><button className={`button ${mode === 'THERMAL' ? 'primary' : 'secondary'}`} type="button" onClick={() => setMode('THERMAL')}>80mm</button><button className="button primary" type="button" onClick={print}>Print</button><button className="button secondary" type="button" onClick={() => setOpen(false)}>Close</button></div></div>
        <div className="print-canvas"><article className="invoice-sheet"><header className="invoice-head"><div><div className="invoice-company">ARTKRILIK WORKS</div><div className="invoice-subtitle">Sales Order Invoice</div></div><div className="invoice-title"><h1>INVOICE</h1><strong>{order.soNumber}</strong></div></header><section className="invoice-meta"><div><div className="invoice-label">Bill To</div><strong>{order.customerName || 'Marketplace'}</strong><div>{order.trackingNumber || '—'}</div></div><div><div className="invoice-label">Order Information</div><div>Order Date: <strong>{formatDate(order.orderDate)}</strong></div><div>Deadline: <strong>{formatDate(order.deadline)}</strong></div><div>Order Type: <strong>{order.orderType}</strong></div><div>Payment Status: <strong>{paymentStatus}</strong></div></div></section><section className="invoice-items"><table><thead><tr><th>PRODUCT</th><th>QTY</th><th>UNIT PRICE</th><th>DISCOUNT</th><th>TOTAL</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.productName}</strong><br /><small>{item.sku || ''}</small></td><td>{item.quantity}</td><td>Rp {money(item.unitPrice)}</td><td>{item.discountType === 'PERCENTAGE' ? `${item.discountValue}%` : `Rp ${money(item.discountValue)}`}</td><td className="invoice-num">Rp {money(item.itemTotal)}</td></tr>)}</tbody></table></section><section className="invoice-totals"><div><span>Subtotal</span><strong>Rp {money(items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0))}</strong></div><div><span>Discount</span><strong>Rp {money(Math.max(0, items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0) - grandTotal))}</strong></div><div className="invoice-grand"><span>Grand Total</span><strong>Rp {money(grandTotal)}</strong></div></section><section className="invoice-payment"><div className="invoice-label">Payment Summary</div><div className="invoice-payment-grid"><div><span>Paid</span><strong>Rp {money(totalPaid)}</strong></div><div><span>Balance</span><strong>Rp {money(balance)}</strong></div><div><span>Status</span><strong>{paymentStatus}</strong></div></div></section>{payments.length > 0 && <section className="invoice-payment-history"><div className="invoice-label">Payment History</div>{payments.map(payment => <div key={payment.id}><span>{payment.paymentNumber} · {payment.paymentMethod}</span><strong>Rp {money(payment.amount)}</strong></div>)}</section>}<footer className="invoice-footer">ARTKRILIK WORKS · Sales Order Invoice · {order.soNumber}</footer></article></div>
      </div>
    </div>}
  </>;
}
