ALTER TABLE products
  ADD COLUMN IF NOT EXISTS length_cm NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS width_cm NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS height_cm NUMERIC(12,2);

ALTER TABLE products
  ALTER COLUMN sku DROP DEFAULT;
