export const AUDIT = Object.freeze({
  SALES_ORDER_CREATED: 'SALES_ORDER_CREATED',
  SALES_ORDER_UPDATED: 'SALES_ORDER_UPDATED',
  SALES_ORDER_CANCELLED: 'SALES_ORDER_CANCELLED',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  WORK_ORDER_CREATED: 'WORK_ORDER_CREATED',
  WORK_ORDER_STARTED: 'WORK_ORDER_STARTED',
  WORK_ORDER_COMPLETED: 'WORK_ORDER_COMPLETED',
  PRODUCTION_EVENT_CREATED: 'PRODUCTION_EVENT_CREATED',
  PACKING_COMPLETED: 'PACKING_COMPLETED',
  HANDOVER_RECORDED: 'HANDOVER_RECORDED',
  SALES_ORDER_COMPLETED: 'SALES_ORDER_COMPLETED',
});
