import React, { useEffect, useMemo, useState } from 'react';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/backend';
const marketplaces = [['SHOPEE','Shopee'],['TOKOPEDIA','Tokopedia'],['TIKTOK_SHOP','TikTok Shop'],['LAZADA','Lazada'],['BLIBLI','Blibli'],['OTHER','Other']];
const PAYMENT_METHODS = ['Cash', 'Transfer', 'QRIS'];
const emptyItem = () => ({ id: '', productId: '', quantity: 1, unitPrice: 0, discountType: 'NOMINAL', discountValue: 0, isCustom: false, productionNotes: '', artworkFileUrl: '', artworkDriveUrl: '' });
function money(value) { return Number(value || 0).toLocaleString('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }); }
function itemTotal(item) { const gross = Number(item.quantity || 0) * Number(item.unitPrice || 0); const discount = item.discountType === 'PERCENTAGE' ? gross * Number(item.discountValue || 0) / 100 : Number(item.discountValue || 0); return Math.max(0, gross - discount); }
function dateValue(value) { if (!value) return ''; const text = String(value); return text.length >= 10 ? text.slice(0, 10) : text; }

export default function EditSalesOrderPage({ order, onCancel, onSaved }) {
  const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]); const [loadingMaster, setLoadingMaster] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [customerId, setCustomerId] = useState(order.customerId || ''); const [marketplace, setMarketplace] = useState(order.marketplace || ''); const [trackingNumber, setTrackingNumber] = useState(order.trackingNumber || '');
  const [orderDate, setOrderDate] = useState(dateValue(order.orderDate)); const [deadline, setDeadline] = useState(dateValue(order.deadline)); const [priority, setPriority] = useState(order.priority || 'REGULAR');
  const [items, setItems] = useState((order.items || []).filter((item) => item.status !== 'INACTIVE').map((item) => ({ id: item.id, productId: item.productId, quantity: item.quantity, unitPrice: item.unitPrice, discountType: item.discountType, discountValue: item.discountValue, isCustom: item.isCustom, productionNotes: item.productionNotes || '', artworkFileUrl: item.artworkFileUrl || '', artworkDriveUrl: item.artworkDriveUrl || '' })));
  const [payments, setPayments] = useState(order.payments || []); const [showPayment, setShowPayment] = useState(false); const [savingPayment, setSavingPayment] = useState(false); const [paymentError, setPaymentError] = useState(''); const [paymentForm, setPaymentForm] = useState({ amount: '', paymentMethod: '', paymentDate: new Date().toISOString().slice(0, 10), referenceNumber: '', notes: '' });

  useEffect(() => { Promise.all([fetch(`${API_BASE_URL}/api/v1/customers?page=1&pageSize=100&status=ACTIVE`).then(r => r.json()), fetch(`${API_BASE_URL}/api/v1/products?page=1&pageSize=100&status=ACTIVE`).then(r => r.json())]).then(([c,p]) => { if (c.error) throw new Error(c.error.message); if (p.error) throw new Error(p.error.message); setCustomers(c.data || []); setProducts(p.data || []); }).catch(e => setError(e.message)).finally(() => setLoadingMaster(false)); }, []);
  const displayProducts = useMemo(() => { const map = new Map(products.map((p) => [p.id, p])); (order.items || []).forEach((item) => { if (!map.has(item.productId)) map.set(item.productId, { id: item.productId, sku: item.sku || '—', name: item.productName || 'Current product', standardPrice: item.unitPrice }); }); return [...map.values()]; }, [products, order.items]);
  const totals = useMemo(() => items.reduce((sum, item) => { const gross = Number(item.quantity || 0) * Number(item.unitPrice || 0); const discount = item.discountType === 'PERCENTAGE' ? gross * Number(item.discountValue || 0) / 100 : Number(item.discountValue || 0); return { subtotal: sum.subtotal + gross, discount: sum.discount + Math.min(discount, gross), total: sum.total + Math.max(0, gross - discount) }; }, { subtotal: 0, discount: 0, total: 0 }), [items]);
  const persistedGrandTotal = (order.items || []).filter((item) => item.status !== 'INACTIVE').reduce((sum, item) => sum + Number(item.itemTotal || 0), 0);
  const totalPaid = order.orderType === 'MARKETPLACE' ? persistedGrandTotal : payments.reduce((sum, payment) => sum + Number(payment.amount || 0), 0);
  const paymentBalance = Math.max(0, persistedGrandTotal - totalPaid);
  const paymentStatus = order.orderType === 'MARKETPLACE' ? 'PAID' : paymentBalance === 0 && persistedGrandTotal > 0 ? 'PAID' : totalPaid > 0 ? 'PARTIALLY PAID' : 'UNPAID';
  const canAddPayment = order.orderType === 'DIRECT' && paymentBalance > 0 && !['COMPLETED', 'INACTIVE'].includes(order.status);

  function updateItem(index, key, value) { setItems(cur => cur.map((item, i) => i === index ? { ...item, [key]: value } : item)); }
  function selectProduct(index, productId) { const product = displayProducts.find(p => p.id === productId); setItems(cur => cur.map((item, i) => i === index ? { ...item, productId, unitPrice: product ? Number(product.standardPrice || item.unitPrice || 0) : item.unitPrice } : item)); }
  function addItem() { setItems(cur => [...cur, emptyItem()]); }
  function removeItem(index) { if (items.length <= 1) return; setItems(cur => cur.filter((_, i) => i !== index)); }
  async function submit(event) { event.preventDefault(); setError(''); if (order.orderType === 'DIRECT' && !customerId) return setError('Customer is required.'); if (order.orderType === 'MARKETPLACE' && (!marketplace || !trackingNumber.trim())) return setError('Marketplace and tracking number are required.'); if (!deadline || deadline < orderDate) return setError('Deadline must be on or after order date.'); if (!items.length || items.some(item => !item.productId || Number(item.quantity) < 1)) return setError('At least one valid product item is required.'); setSaving(true); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${order.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customerId: order.orderType === 'DIRECT' ? customerId : (customerId || null), marketplace: order.orderType === 'MARKETPLACE' ? marketplace : null, trackingNumber: order.orderType === 'MARKETPLACE' ? trackingNumber.trim() : null, orderDate, deadline, priority, items }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to update sales order.'); onSaved(body.data); } catch (e) { setError(e.message); } finally { setSaving(false); } }

  function openPayment() { setPaymentError(''); setPaymentForm({ amount: '', paymentMethod: '', paymentDate: new Date().toISOString().slice(0, 10), referenceNumber: '', notes: '' }); setShowPayment(true); }
  async function savePayment(event) { event.preventDefault(); const amount = Number(paymentForm.amount); if (!Number.isFinite(amount) || amount <= 0 || amount > paymentBalance) { setPaymentError('Payment amount cannot exceed the remaining balance.'); return; } setSavingPayment(true); setPaymentError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${order.id}/payments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...paymentForm, amount }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to add payment.'); setPayments(cur => [...cur, body.data]); setShowPayment(false); setPaymentForm({ amount: '', paymentMethod: '', paymentDate: new Date().toISOString().slice(0, 10), referenceNumber: '', notes: '' }); } catch (e) { setPaymentError(e.message); } finally { setSavingPayment(false); } }

  return <section className="page-section edit-sales-order-page">
    <div className="page-header"><div><p className="eyebrow">SALES / EDIT SALES ORDER</p><h1>Edit Sales Order</h1><p className="page-description">Update transaction data and item production references before production starts.</p></div></div>
    <form onSubmit={submit}>
      <div className="form-card"><div className="section-heading"><div><h2>Order Information</h2><p>{order.soNumber} · {order.orderType}</p></div></div><div className="form-grid">
        {order.orderType === 'DIRECT' ? <label className="form-field"><span>Customer *</span><select value={customerId} onChange={e => setCustomerId(e.target.value)} disabled={loadingMaster}><option value="">Select customer...</option>{customers.map(c => <option key={c.id} value={c.id}>{c.customerCode} — {c.name}</option>)}</select></label> : <><label className="form-field"><span>Marketplace *</span><select value={marketplace} onChange={e => setMarketplace(e.target.value)}>{marketplaces.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label className="form-field"><span>Resi / Tracking Number *</span><input value={trackingNumber} onChange={e => setTrackingNumber(e.target.value)} /></label><label className="form-field"><span>Customer</span><select value={customerId} onChange={e => setCustomerId(e.target.value)} disabled={loadingMaster}><option value="">Optional</option>{customers.map(c => <option key={c.id} value={c.id}>{c.customerCode} — {c.name}</option>)}</select></label></>}
        <label className="form-field"><span>Order Date *</span><input type="date" value={orderDate} onChange={e => setOrderDate(e.target.value)} /></label><label className="form-field"><span>Deadline *</span><input type="date" min={orderDate} value={deadline} onChange={e => setDeadline(e.target.value)} /></label><label className="form-field"><span>Priority *</span><select value={priority} onChange={e => setPriority(e.target.value)}><option value="REGULAR">Regular</option><option value="SAME_DAY">Same Day</option><option value="INSTANT">Instant</option></select></label>
      </div></div>
      <div className="form-card"><div className="section-heading"><div><h2>Items</h2><p>Changes are synchronized to READY FOR PRODUCTION work-order snapshots.</p></div><button className="secondary-button" type="button" onClick={addItem}>+ Add Product</button></div><div className="items-stack">{items.map((item,index) => <div className="item-card" key={item.id || `new-${index}`}><div className="item-header"><strong>Item {index + 1}</strong>{items.length > 1 && <button className="text-danger" type="button" onClick={() => removeItem(index)}>Remove</button>}</div><div className="form-grid">
        <label className="form-field form-field-full"><span>Product *</span><select value={item.productId} onChange={e => selectProduct(index,e.target.value)} disabled={loadingMaster}><option value="">Select product...</option>{displayProducts.map(p => <option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select></label><label className="form-field"><span>Quantity *</span><input type="number" min="1" step="1" value={item.quantity} onChange={e => updateItem(index,'quantity',e.target.value)} /></label><label className="form-field"><span>Unit Price *</span><input type="number" min="0" step="1" value={item.unitPrice} onChange={e => updateItem(index,'unitPrice',e.target.value)} /></label><label className="form-field"><span>Discount Type</span><select value={item.discountType} onChange={e => updateItem(index,'discountType',e.target.value)}><option value="NOMINAL">Nominal</option><option value="PERCENTAGE">Percentage</option></select></label><label className="form-field"><span>Discount Value</span><input type="number" min="0" step="0.01" max={item.discountType === 'PERCENTAGE' ? 100 : undefined} value={item.discountValue} onChange={e => updateItem(index,'discountValue',e.target.value)} /></label><label className="form-field form-field-full"><span>Production Notes</span><textarea rows="2" value={item.productionNotes} onChange={e => updateItem(index,'productionNotes',e.target.value)} /></label><label className="form-field"><span>Artwork File URL</span><input value={item.artworkFileUrl} onChange={e => updateItem(index,'artworkFileUrl',e.target.value)} /></label><label className="form-field"><span>Artwork Drive Link</span><input value={item.artworkDriveUrl} onChange={e => updateItem(index,'artworkDriveUrl',e.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={item.isCustom} onChange={e => updateItem(index,'isCustom',e.target.checked)} /><span>Custom / Special Request</span></label></div><div className="item-total"><span>Item Total</span><strong>{money(itemTotal(item))}</strong></div></div>)}</div></div>
      <div className="summary-card"><div><span>Subtotal</span><strong>{money(totals.subtotal)}</strong></div><div><span>Discount</span><strong>{money(totals.discount)}</strong></div><div className="grand-total"><span>Grand Total</span><strong>{money(totals.total)}</strong></div></div>
      <div className="form-card edit-payment-card"><div className="section-heading"><div><h2>Payment</h2><p>Payment can be added while editing the Sales Order.</p></div>{canAddPayment && <button className="primary-button" type="button" onClick={openPayment}>Add Payment</button>}</div><div className="edit-payment-summary"><div><span>Grand Total</span><strong>{money(persistedGrandTotal)}</strong></div><div><span>Total Paid</span><strong>{money(totalPaid)}</strong></div><div><span>Balance</span><strong>{money(paymentBalance)}</strong></div><div><span>Payment Status</span><strong>{paymentStatus}</strong></div></div>{payments.length > 0 && <ul className="timeline-list">{payments.map(payment => <li key={payment.id}><strong>{payment.paymentNumber}</strong><span>{money(payment.amount)} · {payment.paymentMethod}</span></li>)}</ul>}</div>
      {error && <div className="form-error">{error}</div>}
      <div className="modal-actions"><button className="secondary-button" type="button" onClick={onCancel} disabled={saving || savingPayment}>Cancel</button><button className="primary-button" type="submit" disabled={saving || loadingMaster}>{saving ? 'Updating...' : 'Update Order'}</button></div>
    </form>

    {showPayment && <div className="modal-backdrop" role="presentation"><div className="modal-card" role="dialog" aria-modal="true" aria-labelledby="edit-payment-title"><div className="modal-header"><div><p className="eyebrow">PAYMENT</p><h2 id="edit-payment-title">Add Payment</h2><p>Remaining balance: <strong>{money(paymentBalance)}</strong></p></div><button className="button secondary" type="button" onClick={() => setShowPayment(false)}>Close</button></div>{paymentError && <div className="alert error">{paymentError}</div>}<form className="entity-form" onSubmit={savePayment}><label>Amount<input required min="1" max={paymentBalance} step="1" type="number" value={paymentForm.amount} onChange={e => setPaymentForm({ ...paymentForm, amount: e.target.value })} /></label><label>Payment Method<select required value={paymentForm.paymentMethod} onChange={e => setPaymentForm({ ...paymentForm, paymentMethod: e.target.value })}><option value="">Select method</option>{PAYMENT_METHODS.map(method => <option key={method} value={method}>{method}</option>)}</select></label><label>Payment Date<input required type="date" value={paymentForm.paymentDate} onChange={e => setPaymentForm({ ...paymentForm, paymentDate: e.target.value })} /></label><label>Reference Number<input value={paymentForm.referenceNumber} onChange={e => setPaymentForm({ ...paymentForm, referenceNumber: e.target.value })} /></label><label>Notes<textarea rows="3" value={paymentForm.notes} onChange={e => setPaymentForm({ ...paymentForm, notes: e.target.value })} /></label><div className="modal-actions"><button className="button secondary" type="button" onClick={() => setShowPayment(false)}>Cancel</button><button className="button primary" type="submit" disabled={savingPayment}>{savingPayment ? 'Saving...' : 'Save Payment'}</button></div></form></div></div>}
  </section>;
}
