import React, { useEffect, useMemo, useState } from 'react';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000';
const emptyItem = () => ({ productId: '', quantity: 1, unitPrice: 0, discountType: 'NOMINAL', discountValue: 0, isCustom: false, productionNotes: '', artworkFileUrl: '', artworkDriveUrl: '' });
const marketplaces = [['SHOPEE','Shopee'],['TOKOPEDIA','Tokopedia'],['TIKTOK_SHOP','TikTok Shop'],['LAZADA','Lazada'],['BLIBLI','Blibli'],['OTHER','Other']];
function money(value) { return Number(value || 0).toLocaleString('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }); }

export default function MarketplaceOrderPage({ onCancel, onCreated }) {
  const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]);
  const [customerId, setCustomerId] = useState(''); const [marketplace, setMarketplace] = useState(''); const [trackingNumber, setTrackingNumber] = useState('');
  const [orderDate, setOrderDate] = useState(new Date().toISOString().slice(0, 10)); const [deadline, setDeadline] = useState(''); const [priority, setPriority] = useState('REGULAR');
  const [items, setItems] = useState([emptyItem()]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { Promise.all([fetch(`${API_BASE_URL}/api/v1/customers?page=1&pageSize=100&status=ACTIVE`).then(r=>r.json()), fetch(`${API_BASE_URL}/api/v1/products?page=1&pageSize=100&status=ACTIVE`).then(r=>r.json())]).then(([c,p])=>{ if(c.error) throw new Error(c.error.message); if(p.error) throw new Error(p.error.message); setCustomers(c.data||[]); setProducts(p.data||[]); }).catch(e=>setError(e.message)).finally(()=>setLoading(false)); }, []);
  const totals = useMemo(()=>items.reduce((s,item)=>{const gross=Number(item.quantity||0)*Number(item.unitPrice||0);const discount=item.discountType==='PERCENTAGE'?gross*Number(item.discountValue||0)/100:Number(item.discountValue||0);return {subtotal:s.subtotal+gross,discount:s.discount+Math.min(discount,gross),total:s.total+Math.max(0,gross-discount)}},{subtotal:0,discount:0,total:0}),[items]);
  function updateItem(i,key,value){setItems(cur=>cur.map((x,n)=>n===i?{...x,[key]:value}:x));}
  function selectProduct(i,id){const p=products.find(x=>x.id===id);setItems(cur=>cur.map((x,n)=>n===i?{...x,productId:id,unitPrice:p?Number(p.standardPrice||0):x.unitPrice}:x));}
  function submit(e){e.preventDefault();setError('');if(!marketplace)return setError('Marketplace is required.');if(!trackingNumber.trim())return setError('Tracking number is required.');if(!deadline)return setError('Deadline is required.');if(deadline<orderDate)return setError('Deadline must be on or after order date.');if(!items.length||items.some(x=>!x.productId||Number(x.quantity)<1))return setError('At least one valid product item is required.');setSaving(true);fetch(`${API_BASE_URL}/api/v1/sales-orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderType:'MARKETPLACE',customerId:customerId||null,marketplace,trackingNumber:trackingNumber.trim(),orderDate,deadline,priority,items})}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||'Unable to create marketplace order.');onCreated(b.data);}).catch(e=>setError(e.message)).finally(()=>setSaving(false));}
  return <section className="page-section"><div className="page-header"><div><p className="eyebrow">SALES / MARKETPLACE ORDER</p><h1>Marketplace Order</h1><p className="page-description">Create a marketplace order. Payment is automatically recorded as PAID.</p></div></div>
    <form onSubmit={submit}>
      <div className="form-card"><div className="section-heading"><div><h2>Order Information</h2><p>Marketplace identity, tracking, customer reference, and deadline.</p></div></div><div className="form-grid">
        <label className="form-field"><span>Marketplace *</span><select value={marketplace} onChange={e=>setMarketplace(e.target.value)}><option value="">Select marketplace...</option>{marketplaces.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
        <label className="form-field"><span>Resi / Tracking Number *</span><input value={trackingNumber} onChange={e=>setTrackingNumber(e.target.value)} placeholder="Required" /></label>
        <label className="form-field"><span>Customer</span><select value={customerId} onChange={e=>setCustomerId(e.target.value)} disabled={loading}><option value="">Optional</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customerCode} — {c.name}</option>)}</select></label>
        <label className="form-field"><span>Order Date *</span><input type="date" value={orderDate} onChange={e=>setOrderDate(e.target.value)} /></label>
        <label className="form-field"><span>Deadline *</span><input type="date" min={orderDate} value={deadline} onChange={e=>setDeadline(e.target.value)} /></label>
        <label className="form-field"><span>Priority *</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="REGULAR">Regular</option><option value="SAME_DAY">Same Day</option><option value="INSTANT">Instant</option></select></label>
      </div></div>
      <div className="form-card"><div className="section-heading"><div><h2>Items</h2><p>Products are selected from Product Master.</p></div><button className="secondary-button" type="button" onClick={()=>setItems(cur=>[...cur,emptyItem()])}>+ Add Product</button></div><div className="items-stack">{items.map((item,index)=><div className="item-card" key={index}><div className="item-header"><strong>Item {index+1}</strong>{items.length>1&&<button className="text-danger" type="button" onClick={()=>setItems(cur=>cur.filter((_,i)=>i!==index))}>Remove</button>}</div><div className="form-grid">
        <label className="form-field form-field-full"><span>Product *</span><select value={item.productId} onChange={e=>selectProduct(index,e.target.value)} disabled={loading}><option value="">Select product...</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select></label>
        <label className="form-field"><span>Quantity *</span><input type="number" min="1" step="1" value={item.quantity} onChange={e=>updateItem(index,'quantity',e.target.value)} /></label><label className="form-field"><span>Unit Price *</span><input type="number" min="0" step="1" value={item.unitPrice} onChange={e=>updateItem(index,'unitPrice',e.target.value)} /></label><label className="form-field"><span>Discount Type</span><select value={item.discountType} onChange={e=>updateItem(index,'discountType',e.target.value)}><option value="NOMINAL">Nominal</option><option value="PERCENTAGE">Percentage</option></select></label><label className="form-field"><span>Discount Value</span><input type="number" min="0" step="0.01" value={item.discountValue} onChange={e=>updateItem(index,'discountValue',e.target.value)} /></label>
        <label className="form-field form-field-full"><span>Production Notes</span><textarea rows="2" value={item.productionNotes} onChange={e=>updateItem(index,'productionNotes',e.target.value)} /></label><label className="form-field"><span>Artwork File URL</span><input value={item.artworkFileUrl} onChange={e=>updateItem(index,'artworkFileUrl',e.target.value)} /></label><label className="form-field"><span>Artwork Drive Link</span><input value={item.artworkDriveUrl} onChange={e=>updateItem(index,'artworkDriveUrl',e.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={item.isCustom} onChange={e=>updateItem(index,'isCustom',e.target.checked)} /><span>Custom / Special Request</span></label>
      </div><div className="item-total"><span>Item Total</span><strong>{money(Math.max(0,Number(item.quantity||0)*Number(item.unitPrice||0)-(item.discountType==='PERCENTAGE'?Number(item.quantity||0)*Number(item.unitPrice||0)*Number(item.discountValue||0)/100:Number(item.discountValue||0)))}</strong></div></div>)}</div></div>
      <div className="summary-card"><div><span>Subtotal</span><strong>{money(totals.subtotal)}</strong></div><div><span>Discount</span><strong>{money(totals.discount)}</strong></div><div className="grand-total"><span>Grand Total</span><strong>{money(totals.total)}</strong></div></div><div className="form-note">Marketplace payment status: <strong>PAID</strong></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-button" type="button" onClick={onCancel} disabled={saving}>Cancel</button><button className="primary-button" type="submit" disabled={saving||loading}>{saving?'Creating...':'Create WO'}</button></div>
    </form></section>;
}
