import React, { useCallback, useEffect, useState } from 'react';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000';
const STATUS_LABELS = { NEW_ORDER: 'New Order', READY_PRODUCTION: 'Ready Production', IN_PRODUCTION: 'In Production', PACKING: 'Packing', RTS: 'RTS', COMPLETED: 'Completed', INACTIVE: 'Inactive' };

export default function SalesOrderDetailPage({ salesOrderId, onBack }) {
  const [order, setOrder] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creatingWO, setCreatingWO] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}`); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to load sales order.'); setOrder(body.data); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [salesOrderId]);
  useEffect(() => { load(); }, [load]);
  async function createWorkOrders() { setCreatingWO(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}/work-orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to create work orders.'); await load(); } catch (e) { setError(e.message); } finally { setCreatingWO(false); } }
  if (loading) return <section className="state-card">Loading sales order...</section>;
  if (error || !order) return <section><div className="alert error">{error || 'Sales order not found.'}</div><button className="button secondary" type="button" onClick={onBack}>Back</button></section>;
  const items = order.items || []; const payments = order.payments || []; const workOrders = order.workOrders || []; const grandTotal = items.reduce((sum, item) => sum + Number(item.itemTotal || 0), 0); const totalPaid = payments.reduce((sum, payment) => sum + Number(payment.amount || 0), 0); const balance = Math.max(0, grandTotal - totalPaid); const paymentStatus = order.orderType === 'MARKETPLACE' ? 'PAID' : balance === 0 && grandTotal > 0 ? 'PAID' : totalPaid > 0 ? 'PARTIALLY PAID' : 'UNPAID'; const canCreateWO = order.orderType === 'DIRECT' && order.status === 'NEW_ORDER' && workOrders.length < items.length;
  return <section><div className="page-header"><div><p className="eyebrow">SALES / ORDER DETAIL</p><h1>{order.soNumber}</h1><p>{order.orderType === 'MARKETPLACE' ? `${order.marketplace} · ${order.trackingNumber}` : 'Direct Order'} · Deadline {order.deadline}</p></div><div className="page-actions"><button className="button secondary" type="button" onClick={onBack}>Back</button>{order.status === 'NEW_ORDER' && <button className="button secondary" type="button" disabled>Edit</button>}{canCreateWO && <button className="button primary" type="button" onClick={createWorkOrders} disabled={creatingWO}>{creatingWO ? 'Creating...' : 'Create WO'}</button>}<button className="button secondary" type="button" onClick={() => window.print()}>Print</button></div></div>{error && <div className="error-banner"><span>{error}</span><button type="button" onClick={load}>Retry</button></div>}
    <div className="detail-card-grid"><section className="detail-card"><h2>Order Info</h2><div className="detail-grid"><div><span>Order Type</span><strong>{order.orderType}</strong></div><div><span>Status</span><strong>{STATUS_LABELS[order.status] || order.status}</strong></div><div><span>Order Date</span><strong>{order.orderDate}</strong></div><div><span>Deadline</span><strong>{order.deadline}</strong></div><div><span>Priority</span><strong>{order.priority}</strong></div><div><span>Customer</span><strong>{order.customerName || 'Marketplace'}</strong></div></div></section>
    <section className="detail-card"><h2>Payment</h2><div className="payment-summary"><div><span>Grand Total</span><strong>Rp {grandTotal.toLocaleString('id-ID')}</strong></div><div><span>Total Paid</span><strong>Rp {totalPaid.toLocaleString('id-ID')}</strong></div><div><span>Balance</span><strong>Rp {balance.toLocaleString('id-ID')}</strong></div><div><span>Payment Status</span><strong>{paymentStatus}</strong></div></div>{order.orderType !== 'MARKETPLACE' && <button className="button secondary" type="button" disabled>Add Payment</button>}{payments.length > 0 && <ul className="timeline-list">{payments.map((payment) => <li key={payment.id}><strong>{payment.paymentNumber}</strong><span>Rp {Number(payment.amount).toLocaleString('id-ID')}</span></li>)}</ul>}</section></div>
    <section className="detail-card"><div className="section-heading"><h2>Items</h2><span>{items.length} item{items.length === 1 ? '' : 's'}</span></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Product</th><th>Qty</th><th>Unit Price</th><th>Discount</th><th>Total</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.itemNumber}</td><td><strong>{item.productName}</strong><br /><small>{item.sku}</small></td><td>{item.quantity} {item.productUnit}</td><td>Rp {Number(item.unitPrice).toLocaleString('id-ID')}</td><td>{item.discountType === 'PERCENTAGE' ? `${item.discountValue}%` : `Rp ${Number(item.discountValue).toLocaleString('id-ID')}`}</td><td>Rp {Number(item.itemTotal).toLocaleString('id-ID')}</td></tr>)}</tbody></table></div></section>
    <div className="detail-card-grid"><section className="detail-card"><h2>Artwork & Production Notes</h2>{items.map((item) => <div className="item-note" key={item.id}><strong>Item {item.itemNumber} · {item.productName}</strong><p>{item.isCustom ? 'Custom / Special Request' : 'Standard item'}</p><p>{item.productionNotes || 'No production notes.'}</p><p>{item.artworkFileUrl || item.artworkDriveUrl ? 'Artwork reference available.' : 'No artwork reference.'}</p></div>)}</section><section className="detail-card"><h2>Work Orders</h2>{workOrders.length ? <ul className="timeline-list">{workOrders.map((wo) => <li key={wo.id}><strong>{wo.woNumber}</strong><span>{STATUS_LABELS[wo.status] || wo.status}</span></li>)}</ul> : <p>No active work orders yet.</p>}</section></div>
  </section>;
}
