import React, { useCallback, useEffect, useState } from 'react';
import EditSalesOrderPage from './EditSalesOrderPage.jsx';
import InvoicePrint from '../components/InvoicePrint.jsx';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/backend';
const STATUS_LABELS = { NEW_ORDER: 'New Order', READY_PRODUCTION: 'Ready Production', IN_PRODUCTION: 'In Production', PACKING: 'Packing', RTS: 'RTS', COMPLETED: 'Completed', INACTIVE: 'Inactive' };
function money(value) { return Number(value || 0).toLocaleString('id-ID'); }
function formatDate(value) { if (!value) return '—'; const date = new Date(value); if (Number.isNaN(date.getTime())) return String(value); return new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(date); }

export default function SalesOrderDetailPage({ salesOrderId, onBack }) {
  const [order, setOrder] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creatingWO, setCreatingWO] = useState(false); const [showHandover, setShowHandover] = useState(false); const [showEdit, setShowEdit] = useState(false); const [savingHandover, setSavingHandover] = useState(false); const [completing, setCompleting] = useState(false); const [cancelling, setCancelling] = useState(false); const [handoverError, setHandoverError] = useState(''); const [handoverForm, setHandoverForm] = useState({ handoverType: 'CUSTOMER_PICKUP', notes: '' });
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}`); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to load sales order.'); setOrder(body.data); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [salesOrderId]);
  useEffect(() => { load(); }, [load]);
  async function createWorkOrders() { setCreatingWO(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}/work-orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to create work orders.'); await load(); } catch (e) { setError(e.message); } finally { setCreatingWO(false); } }
  async function cancelOrder() { if (cancelling) return; if (!window.confirm(`Cancel Sales Order ${order.soNumber}? This will mark the order, active items, and related work orders inactive.`)) return; setCancelling(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}/cancel`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to cancel sales order.'); await load(); } catch (e) { setError(e.message); } finally { setCancelling(false); } }
  function openHandover() { setHandoverError(''); setHandoverForm({ handoverType: 'CUSTOMER_PICKUP', notes: '' }); setShowHandover(true); }
  async function saveHandover(event) { event.preventDefault(); setSavingHandover(true); setHandoverError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}/handovers`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(handoverForm) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to record handover.'); setShowHandover(false); await load(); } catch (e) { setHandoverError(e.message); } finally { setSavingHandover(false); } }
  async function completeOrder() { if (completing || !window.confirm(`Complete Sales Order ${order.soNumber}?`)) return; setCompleting(true); setError(''); try { const response = await fetch(`${API_BASE_URL}/api/v1/sales-orders/${salesOrderId}/complete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || 'Unable to complete sales order.'); await load(); } catch (e) { setError(e.message); } finally { setCompleting(false); } }
  if (loading) return <section className="state-card">Loading sales order...</section>;
  if (error || !order) return <section className="detail-page so-detail-reference"><div className="alert error">{error || 'Sales order not found.'}</div><button className="button secondary" type="button" onClick={onBack}>Close</button></section>;
  if (showEdit) return <EditSalesOrderPage order={order} onCancel={() => setShowEdit(false)} onSaved={() => { setShowEdit(false); load(); }} />;

  const items = order.items || []; const payments = order.payments || []; const workOrders = order.workOrders || []; const handovers = order.handovers || []; const activeItems = items.filter(item => item.status !== 'INACTIVE'); const grandTotal = activeItems.reduce((sum, item) => sum + Number(item.itemTotal || 0), 0); const totalPaid = order.orderType === 'MARKETPLACE' ? grandTotal : payments.reduce((sum, payment) => sum + Number(payment.amount || 0), 0); const balance = Math.max(0, grandTotal - totalPaid); const paymentStatus = order.orderType === 'MARKETPLACE' ? 'PAID' : balance === 0 && grandTotal > 0 ? 'PAID' : totalPaid > 0 ? 'PARTIALLY PAID' : 'UNPAID'; const canEdit = ['NEW_ORDER', 'READY_PRODUCTION'].includes(order.status); const canCancel = ['NEW_ORDER', 'READY_PRODUCTION'].includes(order.status); const canCreateWO = order.orderType === 'DIRECT' && order.status === 'NEW_ORDER' && workOrders.length < activeItems.length; const canHandover = order.status === 'RTS' && handovers.length === 0; const canComplete = order.status === 'RTS' && paymentStatus === 'PAID' && handovers.length > 0;
  const customer = order.customerName || 'Marketplace'; const customerMobile = order.customerMobile || order.mobile || '—'; const customerEmail = order.customerEmail || order.email || '—'; const customerAddress = order.customerAddress || order.address || '—';

  return <section className="detail-page so-detail-reference">
    <header className="so-reference-header"><div><p className="eyebrow">SALES / ORDER DETAIL</p><div className="so-reference-number">{order.soNumber}</div><div className="so-reference-customer">{customer}</div><div className="so-reference-context">Order Date {formatDate(order.orderDate)} · Deadline {formatDate(order.deadline)}</div></div><span className="status-badge">{STATUS_LABELS[order.status] || order.status}</span></header>
    {error && <div className="error-banner so-reference-error"><span>{error}</span><button type="button" onClick={load}>Retry</button></div>}
    <div className="so-reference-body">
      <section className="so-reference-section"><div className="so-reference-section-head">Order Information</div><div className="so-reference-section-body so-grid-2"><div><span className="so-info-label">SO Number</span><strong>{order.soNumber}</strong></div><div><span className="so-info-label">Order Date</span><strong>{formatDate(order.orderDate)}</strong></div><div><span className="so-info-label">Deadline</span><strong>{formatDate(order.deadline)}</strong></div><div><span className="so-info-label">Priority</span><strong>{String(order.priority || '—').replaceAll('_', ' ')}</strong></div><div><span className="so-info-label">Order Type</span><strong>{order.orderType === 'MARKETPLACE' ? 'Marketplace Order' : 'Direct Order'}</strong></div><div><span className="so-info-label">Order Status</span><strong>{STATUS_LABELS[order.status] || order.status}</strong></div></div></section>
      <section className="so-reference-section"><div className="so-reference-section-head">Customer Information</div><div className="so-reference-section-body so-grid-2"><div><span className="so-info-label">Customer</span><strong>{customer}</strong></div><div><span className="so-info-label">Mobile</span><strong>{customerMobile}</strong></div><div><span className="so-info-label">Email</span><strong>{customerEmail}</strong></div><div><span className="so-info-label">Address</span><strong>{customerAddress}</strong></div>{order.orderType === 'MARKETPLACE' && <><div><span className="so-info-label">Marketplace</span><strong>{order.marketplace || '—'}</strong></div><div><span className="so-info-label">Tracking</span><strong>{order.trackingNumber || '—'}</strong></div></>}</div></section>
      <section className="so-reference-section"><div className="so-reference-section-head">Order Items</div><div className="so-reference-section-body">{items.map(item => <article className="so-reference-item" key={item.id}><div className="so-reference-item-title"><strong>{item.productName || `Item ${item.itemNumber}`}</strong><span>{item.status === 'INACTIVE' ? 'Inactive' : 'Active'}</span></div><div className="so-reference-item-info"><div><span className="so-info-label">SKU</span><strong>{item.sku || '—'}</strong></div><div><span className="so-info-label">Unit</span><strong>{item.productUnit || '—'}</strong></div><div><span className="so-info-label">Qty</span><strong>{item.quantity}</strong></div><div><span className="so-info-label">Unit Price</span><strong>Rp {money(item.unitPrice)}</strong></div><div><span className="so-info-label">Discount</span><strong>{item.discountType === 'PERCENTAGE' ? `${item.discountValue}%` : `Rp ${money(item.discountValue)}`}</strong></div><div><span className="so-info-label">Total</span><strong>Rp {money(item.itemTotal)}</strong></div><div><span className="so-info-label">Specification</span><strong>{item.isCustom ? 'Custom' : 'Standard'}</strong></div></div><div className="so-reference-attachment"><div className="so-reference-artwork">{item.artworkFileUrl ? <img src={item.artworkFileUrl} alt={`Artwork Item ${item.itemNumber}`} /> : <span>No artwork preview</span>}</div><div className="so-reference-attachment-info"><span className="so-info-label">Google Drive</span>{item.artworkDriveUrl ? <a href={item.artworkDriveUrl} target="_blank" rel="noreferrer">Open artwork / cutting pattern</a> : <strong>—</strong>}<div className="so-reference-notes"><span className="so-info-label">Production Notes</span><div>{item.productionNotes || 'No production notes.'}</div></div></div></div></article>)}</div></section>
      <section className="so-reference-section"><div className="so-reference-section-head">Payment</div><div className="so-reference-section-body"><div className="so-payment-grid"><div><span className="so-info-label">Grand Total</span><strong className="so-amount">Rp {money(grandTotal)}</strong></div><div><span className="so-info-label">Total Paid</span><strong className="so-amount">Rp {money(totalPaid)}</strong></div><div><span className="so-info-label">Balance</span><strong className="so-amount">Rp {money(balance)}</strong></div></div><div className="so-payment-status"><span className="so-info-label">Payment Status</span><strong>{paymentStatus}</strong></div>{payments.length > 0 && <ul className="timeline-list">{payments.map(payment => <li key={payment.id}><strong>{payment.paymentNumber}</strong><span>Rp {money(payment.amount)} · {payment.paymentMethod}</span></li>)}</ul>}</div></section>
      <section className="so-reference-section"><div className="so-reference-section-head">Fulfillment</div><div className="so-reference-section-body so-grid-2"><div><span className="so-info-label">Packing</span><strong>{order.status === 'RTS' || order.status === 'COMPLETED' ? 'Packed' : 'Pending'}</strong></div><div><span className="so-info-label">Handover</span><strong>{handovers.length ? 'Recorded' : 'Pending'}</strong></div><div><span className="so-info-label">Payment</span><strong>{paymentStatus}</strong></div><div><span className="so-info-label">Next Action</span><strong>{order.status === 'RTS' ? (canComplete ? 'Complete Order' : handovers.length ? 'Payment required' : 'Record Handover') : order.status === 'PACKING' ? 'Packing' : order.status === 'COMPLETED' ? 'Completed' : 'Production'}</strong></div></div></section>
      <section className="so-reference-section"><div className="so-reference-section-head">Work Orders</div><div className="so-reference-section-body">{workOrders.length ? <ul className="timeline-list">{workOrders.map(wo => <li key={wo.id}><strong>{wo.woNumber}</strong><span>{wo.status === 'COMPLETED_PRODUCTION' ? 'Completed Production' : STATUS_LABELS[wo.status] || wo.status}</span></li>)}</ul> : <p>No active work orders yet.</p>}</div></section>
    </div>
    <footer className="so-reference-actions"><div>{canCancel && <button className="button secondary text-danger" type="button" onClick={cancelOrder} disabled={cancelling}>{cancelling ? 'Cancelling...' : 'Cancel Order'}</button>}</div><div className="so-reference-actions-right"><InvoicePrint order={order} items={activeItems} payments={payments} grandTotal={grandTotal} totalPaid={totalPaid} balance={balance} paymentStatus={paymentStatus} />{canEdit && <button className="button secondary" type="button" onClick={() => setShowEdit(true)}>Edit Sales Order</button>}{canCreateWO && <button className="button primary" type="button" onClick={createWorkOrders} disabled={creatingWO}>{creatingWO ? 'Creating...' : 'Generate WO'}</button>}{canHandover && <button className="button primary" type="button" onClick={openHandover}>Record Handover</button>}{canComplete && <button className="button primary" type="button" onClick={completeOrder} disabled={completing}>{completing ? 'Completing...' : 'Complete Order'}</button>}</div></footer>
    {showHandover && <div className="modal-backdrop" role="presentation"><div className="modal-card" role="dialog" aria-modal="true" aria-labelledby="handover-title"><div className="modal-header"><div><p className="eyebrow">HANDOVER</p><h2 id="handover-title">Record Handover</h2></div><button className="button secondary" type="button" onClick={() => setShowHandover(false)}>Close</button></div>{handoverError && <div className="alert error">{handoverError}</div>}<form className="entity-form" onSubmit={saveHandover}><label>Handover Type<select value={handoverForm.handoverType} onChange={e => setHandoverForm({ ...handoverForm, handoverType: e.target.value })}><option value="CUSTOMER_PICKUP">Customer Pickup</option><option value="COURIER">Courier</option></select></label><label>Notes<textarea rows="3" value={handoverForm.notes} onChange={e => setHandoverForm({ ...handoverForm, notes: e.target.value })} /></label><div className="modal-actions"><button className="button secondary" type="button" onClick={() => setShowHandover(false)}>Cancel</button><button className="button primary" type="submit" disabled={savingHandover}>{savingHandover ? 'Saving...' : 'Save Handover'}</button></div></form></div></div>}
  </section>;
}
